# Generated by Django 4.0.5 on 2022-06-17 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True)),
                ('hora_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
                ('hora_alteracao', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Número da O.S.')),
                ('pedido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do pedido')),
                ('data_pedido', models.DateField(blank=True, null=True, verbose_name='data do pedido')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='R$')),
                ('imposto', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data da Entrega')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('nota_fiscal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nota Fiscal')),
                ('data_entrega_real', models.DateField(blank=True, null=True, verbose_name='Data de Entrega Real')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrdemServico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False)),
                ('hora_inclusao', models.DateTimeField(blank=True, editable=False)),
                ('data_alteracao', models.DateField(blank=True, editable=False)),
                ('hora_alteracao', models.DateTimeField(blank=True, editable=False)),
                ('numero', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Número da O.S.')),
                ('pedido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do pedido')),
                ('data_pedido', models.DateField(blank=True, null=True, verbose_name='data do pedido')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='R$')),
                ('imposto', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data da Entrega')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('nota_fiscal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nota Fiscal')),
                ('data_entrega_real', models.DateField(blank=True, null=True, verbose_name='Data de Entrega Real')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ordem de Serviço',
                'verbose_name_plural': 'historical Ordens de Serviço',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
