# Generated by Django 4.0.5 on 2022-06-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_alter_historicalordemservico_data_alteracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_ordem_servico', models.CharField(max_length=30, unique=True, verbose_name='Status de O.S.')),
            ],
            options={
                'verbose_name': 'Status de O.S.',
                'verbose_name_plural': 'Status de O.S.',
            },
        ),
    ]
