# Generated by Django 4.0.5 on 2022-06-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0004_rename_status_pedido_statuspedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusPedido',
            new_name='StatusOrdemServico',
        ),
    ]
