# Generated by Django 4.0.5 on 2022-06-18 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0005_rename_statuspedido_statusordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordemservico',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ordens.statusordemservico', verbose_name='Status da O.S.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ordens.statusordemservico', verbose_name='Status da O.S.'),
            preserve_default=False,
        ),
    ]
