# Generated by Django 4.0.5 on 2022-06-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0007_alter_historicalordemservico_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordemservico',
            name='numero',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='Número da O.S.'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='numero',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Número da O.S.'),
        ),
    ]
