# Generated by Django 4.0.5 on 2022-06-15 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True)),
                ('hora_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
                ('hora_alteracao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('cpf', django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False)),
                ('hora_inclusao', models.DateTimeField(blank=True, editable=False)),
                ('data_alteracao', models.DateField(blank=True, editable=False)),
                ('hora_alteracao', models.DateTimeField(blank=True, editable=False)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('cpf', django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cliente',
                'verbose_name_plural': 'historical clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
