# Generated by Django 4.0.5 on 2022-06-22 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_cnpj_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
    ]
